### ISSUE TITLE
Does not work with actual elixir version

### ISSUE THREAD

**Issue by texxlan** [MikeyAlder/laravel-elixir-typescript#3]
First error running gulp:
`Error: Cannot find module 'laravel-elixir/ingredients/commands/Notification`

**Comment by okaufmann** [comment]
+1

**Comment by jvanharn** [comment]
+1

**Comment by mikeygcooper** [comment]
Sorry for taking a while to get back to you all ... I'm not actively developing this anymore, however okaufmann has forked and created an updated version that you can use https://github.com/okaufmann/laravel-elixir-typescript
