### ISSUE TITLE
Remove NPM package so i can use name 'laravel-elixir-typescript'

### ISSUE THREAD

**Issue by okaufmann** [MikeyAlder/laravel-elixir-typescript#7]
Hi Mike

Could you remove your package from npm? I would like to use the name `laravel-elixir-typescript` for my fork which is still maintained.

Thanks for your support.

**Comment by mikeygcooper** [comment]
Hi,

It won't let me delete the package due to NPM new policy. I can transfer the ownership to you if you let me know your npm username.

:)

**Comment by okaufmann** [comment]
its okaufmann, thank you

**Comment by mikeygcooper** [comment]
I've added you as an owner to the package. I haven't removed my access yet just in case you couldn't get access. Feel free to remove me when you've tested you have the correct permissions.
